
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HomePlan.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Photo
{

    public System.Guid PhotoId { get; set; }

    public System.Guid UserId { get; set; }

    public string Photolocation { get; set; }



    public virtual User User { get; set; }

}

}
