//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomePlan.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanActivity
    {
        public PlanActivity()
        {
            this.ActualActivities = new HashSet<PlanActivity>();
        }
    
        public System.Guid PlanActivityID { get; set; }
        public System.Guid PlanID { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int Order { get; set; }
        public HomePlan.Shared.Enumerations.PlanActivityType Type { get; set; }
        public Nullable<System.Guid> UserActivityID { get; set; }
        public Nullable<System.Guid> PlannedActivityID { get; set; }
        public bool IsActual { get; set; }
    
        public virtual Plan Plan { get; set; }
        public virtual UserActivity UserActivity { get; set; }
        public virtual ICollection<PlanActivity> ActualActivities { get; set; }
        public virtual PlanActivity PlannedActivity { get; set; }
    }
}
