//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomePlan.Entities
{
    using System;
    
    public enum PlanActivityType : byte
    {
        WorkRelated = 1,
        Personal = 2,
        Incidental = 3
    }
}
