
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HomePlan.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Plan
{

    public Plan()
    {

        this.PlanActivities = new HashSet<PlanActivity>();

    }


    public System.Guid PlanID { get; set; }

    public System.Guid UserID { get; set; }

    public System.DateTime StartDateTime { get; set; }

    public System.DateTime EndDateTime { get; set; }



    public virtual User User { get; set; }

    public virtual ICollection<PlanActivity> PlanActivities { get; set; }

}

}
