
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HomePlan.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public User()
    {

        this.Photos = new HashSet<Photo>();

        this.Plans = new HashSet<Plan>();

        this.UserActivities = new HashSet<UserActivity>();

    }


    public System.Guid UserID { get; set; }

    public string Email { get; set; }

    public string UserName { get; set; }

    public string AvatarImage { get; set; }

    public string Password { get; set; }



    public virtual ICollection<Photo> Photos { get; set; }

    public virtual ICollection<Plan> Plans { get; set; }

    public virtual ICollection<UserActivity> UserActivities { get; set; }

}

}
