CREATE TABLE [dbo].[Photo]
(
	[PhotoId] UNIQUEIDENTIFIER CONSTRAINT [DF_PHOTOID] DEFAULT NEWID() NOT NULL PRIMARY KEY,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[Photolocation] varchar(255),
	CONSTRAINT [PK_Photo] PRIMARY KEY (PhotoId),
	CONSTRAINT [FK_Photo_User] FOREIGN KEY(UserId) REFERENCES [User](UserId)
)
