CREATE TABLE [dbo].[Plan]
(
	[PlanID] UNIQUEIDENTIFIER NOT NULL
		CONSTRAINT [DF_Plan_PlanID] DEFAULT NEWID()
		CONSTRAINT [PK_Plan] PRIMARY KEY,
	[UserID] UNIQUEIDENTIFIER NOT NULL,
	[StartDateTime] DATETIME NOT NULL,
	[EndDateTime] DATETIME NOT NULL,

	CONSTRAINT [FK_Plan_User] FOREIGN KEY(UserID) REFERENCES [User](UserID)
)
